// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpk7-JvbNCTXUJ2wMvJobtMiNh9-WPnfc',
    appId: '1:783297749108:web:86941527d3afda39777121',
    messagingSenderId: '783297749108',
    projectId: 'electromec-sos-1',
    authDomain: 'electromec-sos-1.firebaseapp.com',
    storageBucket: 'electromec-sos-1.firebasestorage.app',
    measurementId: 'G-CG85PZ65XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA54mYwjAI7aJPywfsUIwQVAgH_trMPWFM',
    appId: '1:783297749108:android:8ce67b7939882eb1777121',
    messagingSenderId: '783297749108',
    projectId: 'electromec-sos-1',
    storageBucket: 'electromec-sos-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKqcEF35uCXWUbdFCqNtmLC7jUwyZnnAk',
    appId: '1:783297749108:ios:6e1bd802c7b59369777121',
    messagingSenderId: '783297749108',
    projectId: 'electromec-sos-1',
    storageBucket: 'electromec-sos-1.firebasestorage.app',
    iosBundleId: 'com.example.electronicsService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKqcEF35uCXWUbdFCqNtmLC7jUwyZnnAk',
    appId: '1:783297749108:ios:6e1bd802c7b59369777121',
    messagingSenderId: '783297749108',
    projectId: 'electromec-sos-1',
    storageBucket: 'electromec-sos-1.firebasestorage.app',
    iosBundleId: 'com.example.electronicsService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpk7-JvbNCTXUJ2wMvJobtMiNh9-WPnfc',
    appId: '1:783297749108:web:d4f64835c1216f67777121',
    messagingSenderId: '783297749108',
    projectId: 'electromec-sos-1',
    authDomain: 'electromec-sos-1.firebaseapp.com',
    storageBucket: 'electromec-sos-1.firebasestorage.app',
    measurementId: 'G-EC41MWQTGN',
  );
}
